version: "2.1"
services:
  calibre-web:
    image: ghcr.io/linuxserver/calibre-web
    container_name: calibre-web
    env_file:
      - calibre.env
    volumes:
      - calibre_config:/config
      - calibre_library:/books
    ports:
      - 8083:8083
    restart: unless-stopped

volumes:
  calibre_config:
  calibre_library:
