version: "3.5"
services:
  jellyfin:
    image: jellyfin/jellyfin
    container_name: jellyfin
    user: 1000:1000
    network_mode: "host"
    volumes:
      - jellyfin_config:/config
      - jellyfin_cache:/cache
      - jellyfin_media:/media
      - jellyfin_media2:/media2:ro
    restart: "unless-stopped"
    env_file:
      - jellyfin.env

volumes:
  jellyfin_config:
  jellyfin_cache:
  jellyfin_media:
  jellyfin_media2:
